//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidtermAssesment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int RecommendationID { get; set; }
        public int User_Id { get; set; }
        public int BookID { get; set; }
        public string Reasons { get; set; }
    
        public virtual User User { get; set; }
    }
}
